---


  - name: set_power_state
    remote_user: "{{ drac_ssh_user }}"
    raw: racadm serveraction "{{ powerstate }}"
    failed_when: "'ERROR' in result.stdout or 'COMMAND PROCESSING FAILED' in result.stdout or 'error' in result.stdout or result.rc != 0"

